<?xml version="1.0" encoding="utf-8"?><Database Name="AJDNNDatabase_v5" Class="skrivbokenLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=AJDNNDatabase_v5;User ID=forfAdmin4" SettingsObjectName="krypinSkrivboken.My.MySettings" SettingsPropertyName="AJDNNDatabase_v5ConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAJBarnensSkrivCategory" Member="tblAJBarnensSkrivCategories">
    <Type Name="tblAJBarnensSkrivCategory">
      <Column Name="catid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="catimg" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="catcolor" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="catactive" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAJBarnensSkriv" Member="tblAJBarnensSkrivs">
    <Type Name="tblAJBarnensSkriv">
      <Column Name="SkrivID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Inserted" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Story" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Approved" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gillar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publish" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserRoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsTrialUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsOwner" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UsersOnline" Member="UsersOnlines">
    <Type Name="UsersOnline">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TabID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastActiveDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.AJBarnensSkrivCRUD" Method="AJBarnensSkrivCRUD">
    <Parameter Name="typ" Type="System.Int32" DbType="Int" />
    <Parameter Name="SkrivID" Parameter="skrivID" Type="System.Int32" DbType="Int" />
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Inserted" Parameter="inserted" Type="System.DateTime" DbType="Date" />
    <Parameter Name="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="story" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Category" Parameter="category" Type="System.Int32" DbType="Int" />
    <Parameter Name="Approved" Parameter="approved" Type="System.Int32" DbType="Int" />
    <Parameter Name="Gillar" Parameter="gillar" Type="System.Int32" DbType="Int" />
    <Parameter Name="publish" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AJ_BB_Krypin_skrivbok_byUserid" Method="AJ_BB_Krypin_skrivbok_byUserid">
    <Parameter Name="typ" Type="System.Int32" DbType="Int" />
    <Parameter Name="userid" Type="System.Int32" DbType="Int" />
    <Parameter Name="approved" Type="System.Int32" DbType="Int" />
    <Parameter Name="publish" Type="System.Int32" DbType="Int" />
    <ElementType Name="AJ_BB_Krypin_skrivbok_byUseridResult">
      <Column Name="SkrivID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Inserted" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Story" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Approved" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gillar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publish" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AJ_BB_Krypin_skrivbok_byCategory" Method="AJ_BB_Krypin_skrivbok_byCategory">
    <Parameter Name="Category" Parameter="category" Type="System.Int32" DbType="Int" />
    <Parameter Name="approved" Type="System.Int32" DbType="Int" />
    <Parameter Name="publish" Type="System.Int32" DbType="Int" />
    <ElementType Name="AJ_BB_Krypin_skrivbok_byCategoryResult">
      <Column Name="SkrivID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Inserted" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Story" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Approved" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gillar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publish" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AJ_BB_Krypin_skrivbok_bySkrivID" Method="AJ_BB_Krypin_skrivbok_bySkrivID">
    <Parameter Name="skrivID" Type="System.Int32" DbType="Int" />
    <ElementType Name="AJ_BB_Krypin_skrivbok_bySkrivIDResult">
      <Column Name="SkrivID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Inserted" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Story" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Approved" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gillar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publish" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AJ_BB_Krypin_skrivbok_byAdmin" Method="AJ_BB_Krypin_skrivbok_byAdmin">
    <Parameter Name="typ" Type="System.Int32" DbType="Int" />
    <Parameter Name="approved" Type="System.Int32" DbType="Int" />
    <ElementType Name="AJ_BB_Krypin_skrivbok_byAdminResult">
      <Column Name="SkrivID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Inserted" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Story" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Approved" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gillar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publish" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>