<?xml version="1.0" encoding="utf-8"?><Database Name="AJDNNDatabase_v5" Class="bokmarkelserLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=asusi7-andreas\sqlexpress;Initial Catalog=AJDNNDatabase_v5;User ID=forfAdmin2" SettingsObjectName="BibbloMoney.My.MySettings" SettingsPropertyName="AJDNNDatabase_v5ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAjBokmarkelser" Member="tblAjBokmarkelsers">
    <Type Name="tblAjBokmarkelser">
      <Column Name="Aid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Awardname" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Levels" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Beskrivning" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Occurs" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Badgesrc" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Awardgroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAjBokmarkelserPointCounter" Member="tblAjBokmarkelserPointCounters">
    <Type Name="tblAjBokmarkelserPointCounter">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Aid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Counters" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Levels" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblAjBokmarkelseGrupper" Member="tblAjBokmarkelseGruppers">
    <Type Name="tblAjBokmarkelseGrupper">
      <Column Name="AwardGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AwardGroup" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Occures" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PointEarned" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ToLevelUp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BibblimoneyEarnID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ajbokmarkelserPointEarned" Method="ajbokmarkelserPointEarned">
    <Parameter Name="awardid" Type="System.Int32" DbType="Int" />
    <ElementType Name="ajbokmarkelserPointEarnedResult">
      <Column Name="PointEarned" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AwardGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AwardGroup" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Occures" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ToLevelUp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BibblimoneyEarnID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ajbokmarkelser" Method="ajbokmarkelser">
    <Parameter Name="typ" Type="System.Int32" DbType="Int" />
    <Parameter Name="userid" Type="System.Int32" DbType="Int" />
    <Parameter Name="awardid" Type="System.Int32" DbType="Int" />
    <ElementType Name="ajbokmarkelserResult">
      <Column Name="Userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Aid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Counters" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Levels" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Awardname" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Beskrivning" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Badgesrc" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Occurs" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Awardgroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BibblimoneyEarnID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>