'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="AJDNNDatabase_v5")>  _
Partial Public Class KrypinSettingsLinqDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InserttblAJKrypinUserData(instance As tblAJKrypinUserData)
    End Sub
  Partial Private Sub UpdatetblAJKrypinUserData(instance As tblAJKrypinUserData)
    End Sub
  Partial Private Sub DeletetblAJKrypinUserData(instance As tblAJKrypinUserData)
    End Sub
  Partial Private Sub InserttblAjKrypinAvatar(instance As tblAjKrypinAvatar)
    End Sub
  Partial Private Sub UpdatetblAjKrypinAvatar(instance As tblAjKrypinAvatar)
    End Sub
  Partial Private Sub DeletetblAjKrypinAvatar(instance As tblAjKrypinAvatar)
    End Sub
  Partial Private Sub InserttblAJKrypinSkin(instance As tblAJKrypinSkin)
    End Sub
  Partial Private Sub UpdatetblAJKrypinSkin(instance As tblAJKrypinSkin)
    End Sub
  Partial Private Sub DeletetblAJKrypinSkin(instance As tblAJKrypinSkin)
    End Sub
  Partial Private Sub InserttblAjKrypinUserSetting(instance As tblAjKrypinUserSetting)
    End Sub
  Partial Private Sub UpdatetblAjKrypinUserSetting(instance As tblAjKrypinUserSetting)
    End Sub
  Partial Private Sub DeletetblAjKrypinUserSetting(instance As tblAjKrypinUserSetting)
    End Sub
  Partial Private Sub InserttblAjKrypinUserSettingsTyper(instance As tblAjKrypinUserSettingsTyper)
    End Sub
  Partial Private Sub UpdatetblAjKrypinUserSettingsTyper(instance As tblAjKrypinUserSettingsTyper)
    End Sub
  Partial Private Sub DeletetblAjKrypinUserSettingsTyper(instance As tblAjKrypinUserSettingsTyper)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.KrypinSettings.My.MySettings.Default.AJDNNDatabase_v5ConnectionString1, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property tblAJKrypinUserDatas() As System.Data.Linq.Table(Of tblAJKrypinUserData)
		Get
			Return Me.GetTable(Of tblAJKrypinUserData)
		End Get
	End Property
	
	Public ReadOnly Property tblAjKrypinAvatars() As System.Data.Linq.Table(Of tblAjKrypinAvatar)
		Get
			Return Me.GetTable(Of tblAjKrypinAvatar)
		End Get
	End Property
	
	Public ReadOnly Property tblAJKrypinSkins() As System.Data.Linq.Table(Of tblAJKrypinSkin)
		Get
			Return Me.GetTable(Of tblAJKrypinSkin)
		End Get
	End Property
	
	Public ReadOnly Property tblAjKrypinUserSettings() As System.Data.Linq.Table(Of tblAjKrypinUserSetting)
		Get
			Return Me.GetTable(Of tblAjKrypinUserSetting)
		End Get
	End Property
	
	Public ReadOnly Property tblAjKrypinUserSettingsTypers() As System.Data.Linq.Table(Of tblAjKrypinUserSettingsTyper)
		Get
			Return Me.GetTable(Of tblAjKrypinUserSettingsTyper)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.AjKrypinGetUserKrypin")>  _
	Public Function AjKrypinGetUserKrypin(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal userid As System.Nullable(Of Integer)) As ISingleResult(Of AjKrypinGetUserKrypinResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), userid)
		Return CType(result.ReturnValue,ISingleResult(Of AjKrypinGetUserKrypinResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.AJKrypin_updateAvatarSetting")>  _
	Public Function AJKrypin_updateAvatarSetting() As ISingleResult(Of AJKrypin_updateAvatarSettingResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of AJKrypin_updateAvatarSettingResult))
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblAJKrypinUserData")>  _
Partial Public Class tblAJKrypinUserData
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KrypID As Integer
	
	Private _UserId As Integer
	
	Private _Presentation As String
	
	Private _BBUserMess As String
	
	Private _Avatar As String
	
	Private _ValdUserCss As System.Nullable(Of Integer)
	
	Private _KrypinBehorighet As Integer
	
	Private _LaserJustnu As System.Nullable(Of Integer)
	
	Private _Visits As System.Nullable(Of Integer)
	
	Private _MeVisits As System.Nullable(Of Integer)
	
	Private _ShowMess As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKrypIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnKrypIDChanged()
    End Sub
    Partial Private Sub OnUserIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnUserIdChanged()
    End Sub
    Partial Private Sub OnPresentationChanging(value As String)
    End Sub
    Partial Private Sub OnPresentationChanged()
    End Sub
    Partial Private Sub OnBBUserMessChanging(value As String)
    End Sub
    Partial Private Sub OnBBUserMessChanged()
    End Sub
    Partial Private Sub OnAvatarChanging(value As String)
    End Sub
    Partial Private Sub OnAvatarChanged()
    End Sub
    Partial Private Sub OnValdUserCssChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnValdUserCssChanged()
    End Sub
    Partial Private Sub OnKrypinBehorighetChanging(value As Integer)
    End Sub
    Partial Private Sub OnKrypinBehorighetChanged()
    End Sub
    Partial Private Sub OnLaserJustnuChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLaserJustnuChanged()
    End Sub
    Partial Private Sub OnVisitsChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnVisitsChanged()
    End Sub
    Partial Private Sub OnMeVisitsChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnMeVisitsChanged()
    End Sub
    Partial Private Sub OnShowMessChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnShowMessChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KrypID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property KrypID() As Integer
		Get
			Return Me._KrypID
		End Get
		Set
			If ((Me._KrypID = value)  _
						= false) Then
				Me.OnKrypIDChanging(value)
				Me.SendPropertyChanging
				Me._KrypID = value
				Me.SendPropertyChanged("KrypID")
				Me.OnKrypIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserId", DbType:="Int NOT NULL")>  _
	Public Property UserId() As Integer
		Get
			Return Me._UserId
		End Get
		Set
			If ((Me._UserId = value)  _
						= false) Then
				Me.OnUserIdChanging(value)
				Me.SendPropertyChanging
				Me._UserId = value
				Me.SendPropertyChanged("UserId")
				Me.OnUserIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Presentation", DbType:="NVarChar(500)")>  _
	Public Property Presentation() As String
		Get
			Return Me._Presentation
		End Get
		Set
			If (String.Equals(Me._Presentation, value) = false) Then
				Me.OnPresentationChanging(value)
				Me.SendPropertyChanging
				Me._Presentation = value
				Me.SendPropertyChanged("Presentation")
				Me.OnPresentationChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BBUserMess", DbType:="NVarChar(255)")>  _
	Public Property BBUserMess() As String
		Get
			Return Me._BBUserMess
		End Get
		Set
			If (String.Equals(Me._BBUserMess, value) = false) Then
				Me.OnBBUserMessChanging(value)
				Me.SendPropertyChanging
				Me._BBUserMess = value
				Me.SendPropertyChanged("BBUserMess")
				Me.OnBBUserMessChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Avatar", DbType:="NVarChar(255)")>  _
	Public Property Avatar() As String
		Get
			Return Me._Avatar
		End Get
		Set
			If (String.Equals(Me._Avatar, value) = false) Then
				Me.OnAvatarChanging(value)
				Me.SendPropertyChanging
				Me._Avatar = value
				Me.SendPropertyChanged("Avatar")
				Me.OnAvatarChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValdUserCss", DbType:="Int")>  _
	Public Property ValdUserCss() As System.Nullable(Of Integer)
		Get
			Return Me._ValdUserCss
		End Get
		Set
			If (Me._ValdUserCss.Equals(value) = false) Then
				Me.OnValdUserCssChanging(value)
				Me.SendPropertyChanging
				Me._ValdUserCss = value
				Me.SendPropertyChanged("ValdUserCss")
				Me.OnValdUserCssChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KrypinBehorighet", DbType:="Int NOT NULL")>  _
	Public Property KrypinBehorighet() As Integer
		Get
			Return Me._KrypinBehorighet
		End Get
		Set
			If ((Me._KrypinBehorighet = value)  _
						= false) Then
				Me.OnKrypinBehorighetChanging(value)
				Me.SendPropertyChanging
				Me._KrypinBehorighet = value
				Me.SendPropertyChanged("KrypinBehorighet")
				Me.OnKrypinBehorighetChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LaserJustnu", DbType:="Int")>  _
	Public Property LaserJustnu() As System.Nullable(Of Integer)
		Get
			Return Me._LaserJustnu
		End Get
		Set
			If (Me._LaserJustnu.Equals(value) = false) Then
				Me.OnLaserJustnuChanging(value)
				Me.SendPropertyChanging
				Me._LaserJustnu = value
				Me.SendPropertyChanged("LaserJustnu")
				Me.OnLaserJustnuChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Visits", DbType:="Int")>  _
	Public Property Visits() As System.Nullable(Of Integer)
		Get
			Return Me._Visits
		End Get
		Set
			If (Me._Visits.Equals(value) = false) Then
				Me.OnVisitsChanging(value)
				Me.SendPropertyChanging
				Me._Visits = value
				Me.SendPropertyChanged("Visits")
				Me.OnVisitsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MeVisits", DbType:="Int")>  _
	Public Property MeVisits() As System.Nullable(Of Integer)
		Get
			Return Me._MeVisits
		End Get
		Set
			If (Me._MeVisits.Equals(value) = false) Then
				Me.OnMeVisitsChanging(value)
				Me.SendPropertyChanging
				Me._MeVisits = value
				Me.SendPropertyChanged("MeVisits")
				Me.OnMeVisitsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShowMess", DbType:="Int")>  _
	Public Property ShowMess() As System.Nullable(Of Integer)
		Get
			Return Me._ShowMess
		End Get
		Set
			If (Me._ShowMess.Equals(value) = false) Then
				Me.OnShowMessChanging(value)
				Me.SendPropertyChanging
				Me._ShowMess = value
				Me.SendPropertyChanged("ShowMess")
				Me.OnShowMessChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblAjKrypinAvatars")>  _
Partial Public Class tblAjKrypinAvatar
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Avatarid As Integer
	
	Private _Avatarnamn As String
	
	Private _Avatarsrc As String
	
	Private _Beskrivning As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnAvataridChanging(value As Integer)
    End Sub
    Partial Private Sub OnAvataridChanged()
    End Sub
    Partial Private Sub OnAvatarnamnChanging(value As String)
    End Sub
    Partial Private Sub OnAvatarnamnChanged()
    End Sub
    Partial Private Sub OnAvatarsrcChanging(value As String)
    End Sub
    Partial Private Sub OnAvatarsrcChanged()
    End Sub
    Partial Private Sub OnBeskrivningChanging(value As String)
    End Sub
    Partial Private Sub OnBeskrivningChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Avatarid", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property Avatarid() As Integer
		Get
			Return Me._Avatarid
		End Get
		Set
			If ((Me._Avatarid = value)  _
						= false) Then
				Me.OnAvataridChanging(value)
				Me.SendPropertyChanging
				Me._Avatarid = value
				Me.SendPropertyChanged("Avatarid")
				Me.OnAvataridChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Avatarnamn", DbType:="NVarChar(50)")>  _
	Public Property Avatarnamn() As String
		Get
			Return Me._Avatarnamn
		End Get
		Set
			If (String.Equals(Me._Avatarnamn, value) = false) Then
				Me.OnAvatarnamnChanging(value)
				Me.SendPropertyChanging
				Me._Avatarnamn = value
				Me.SendPropertyChanged("Avatarnamn")
				Me.OnAvatarnamnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Avatarsrc", DbType:="NVarChar(250)")>  _
	Public Property Avatarsrc() As String
		Get
			Return Me._Avatarsrc
		End Get
		Set
			If (String.Equals(Me._Avatarsrc, value) = false) Then
				Me.OnAvatarsrcChanging(value)
				Me.SendPropertyChanging
				Me._Avatarsrc = value
				Me.SendPropertyChanged("Avatarsrc")
				Me.OnAvatarsrcChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Beskrivning", DbType:="NVarChar(250)")>  _
	Public Property Beskrivning() As String
		Get
			Return Me._Beskrivning
		End Get
		Set
			If (String.Equals(Me._Beskrivning, value) = false) Then
				Me.OnBeskrivningChanging(value)
				Me.SendPropertyChanging
				Me._Beskrivning = value
				Me.SendPropertyChanged("Beskrivning")
				Me.OnBeskrivningChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblAJKrypinSkin")>  _
Partial Public Class tblAJKrypinSkin
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _skinID As Integer
	
	Private _Skinnamn As String
	
	Private _Skinsrc As String
	
	Private _Skinclass As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnskinIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnskinIDChanged()
    End Sub
    Partial Private Sub OnSkinnamnChanging(value As String)
    End Sub
    Partial Private Sub OnSkinnamnChanged()
    End Sub
    Partial Private Sub OnSkinsrcChanging(value As String)
    End Sub
    Partial Private Sub OnSkinsrcChanged()
    End Sub
    Partial Private Sub OnSkinclassChanging(value As String)
    End Sub
    Partial Private Sub OnSkinclassChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_skinID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property skinID() As Integer
		Get
			Return Me._skinID
		End Get
		Set
			If ((Me._skinID = value)  _
						= false) Then
				Me.OnskinIDChanging(value)
				Me.SendPropertyChanging
				Me._skinID = value
				Me.SendPropertyChanged("skinID")
				Me.OnskinIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Skinnamn", DbType:="NVarChar(150)")>  _
	Public Property Skinnamn() As String
		Get
			Return Me._Skinnamn
		End Get
		Set
			If (String.Equals(Me._Skinnamn, value) = false) Then
				Me.OnSkinnamnChanging(value)
				Me.SendPropertyChanging
				Me._Skinnamn = value
				Me.SendPropertyChanged("Skinnamn")
				Me.OnSkinnamnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Skinsrc", DbType:="NVarChar(250)")>  _
	Public Property Skinsrc() As String
		Get
			Return Me._Skinsrc
		End Get
		Set
			If (String.Equals(Me._Skinsrc, value) = false) Then
				Me.OnSkinsrcChanging(value)
				Me.SendPropertyChanging
				Me._Skinsrc = value
				Me.SendPropertyChanged("Skinsrc")
				Me.OnSkinsrcChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Skinclass", DbType:="NVarChar(50)")>  _
	Public Property Skinclass() As String
		Get
			Return Me._Skinclass
		End Get
		Set
			If (String.Equals(Me._Skinclass, value) = false) Then
				Me.OnSkinclassChanging(value)
				Me.SendPropertyChanging
				Me._Skinclass = value
				Me.SendPropertyChanged("Skinclass")
				Me.OnSkinclassChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblAjKrypinUserSettings")>  _
Partial Public Class tblAjKrypinUserSetting
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _settingID As Integer
	
	Private _userid As System.Nullable(Of Integer)
	
	Private _settingTypID As System.Nullable(Of Integer)
	
	Private _settingValue As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnsettingIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnsettingIDChanged()
    End Sub
    Partial Private Sub OnuseridChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnuseridChanged()
    End Sub
    Partial Private Sub OnsettingTypIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnsettingTypIDChanged()
    End Sub
    Partial Private Sub OnsettingValueChanging(value As String)
    End Sub
    Partial Private Sub OnsettingValueChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_settingID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property settingID() As Integer
		Get
			Return Me._settingID
		End Get
		Set
			If ((Me._settingID = value)  _
						= false) Then
				Me.OnsettingIDChanging(value)
				Me.SendPropertyChanging
				Me._settingID = value
				Me.SendPropertyChanged("settingID")
				Me.OnsettingIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_userid", DbType:="Int")>  _
	Public Property userid() As System.Nullable(Of Integer)
		Get
			Return Me._userid
		End Get
		Set
			If (Me._userid.Equals(value) = false) Then
				Me.OnuseridChanging(value)
				Me.SendPropertyChanging
				Me._userid = value
				Me.SendPropertyChanged("userid")
				Me.OnuseridChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_settingTypID", DbType:="Int")>  _
	Public Property settingTypID() As System.Nullable(Of Integer)
		Get
			Return Me._settingTypID
		End Get
		Set
			If (Me._settingTypID.Equals(value) = false) Then
				Me.OnsettingTypIDChanging(value)
				Me.SendPropertyChanging
				Me._settingTypID = value
				Me.SendPropertyChanged("settingTypID")
				Me.OnsettingTypIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_settingValue", DbType:="NVarChar(250)")>  _
	Public Property settingValue() As String
		Get
			Return Me._settingValue
		End Get
		Set
			If (String.Equals(Me._settingValue, value) = false) Then
				Me.OnsettingValueChanging(value)
				Me.SendPropertyChanging
				Me._settingValue = value
				Me.SendPropertyChanged("settingValue")
				Me.OnsettingValueChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblAjKrypinUserSettingsTyper")>  _
Partial Public Class tblAjKrypinUserSettingsTyper
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _SetId As Integer
	
	Private _Settingtyp As String
	
	Private _SettingValuetyp As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnSetIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnSetIdChanged()
    End Sub
    Partial Private Sub OnSettingtypChanging(value As String)
    End Sub
    Partial Private Sub OnSettingtypChanged()
    End Sub
    Partial Private Sub OnSettingValuetypChanging(value As String)
    End Sub
    Partial Private Sub OnSettingValuetypChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SetId", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property SetId() As Integer
		Get
			Return Me._SetId
		End Get
		Set
			If ((Me._SetId = value)  _
						= false) Then
				Me.OnSetIdChanging(value)
				Me.SendPropertyChanging
				Me._SetId = value
				Me.SendPropertyChanged("SetId")
				Me.OnSetIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Settingtyp", DbType:="NVarChar(50)")>  _
	Public Property Settingtyp() As String
		Get
			Return Me._Settingtyp
		End Get
		Set
			If (String.Equals(Me._Settingtyp, value) = false) Then
				Me.OnSettingtypChanging(value)
				Me.SendPropertyChanging
				Me._Settingtyp = value
				Me.SendPropertyChanged("Settingtyp")
				Me.OnSettingtypChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SettingValuetyp", DbType:="NVarChar(150)")>  _
	Public Property SettingValuetyp() As String
		Get
			Return Me._SettingValuetyp
		End Get
		Set
			If (String.Equals(Me._SettingValuetyp, value) = false) Then
				Me.OnSettingValuetypChanging(value)
				Me.SendPropertyChanging
				Me._SettingValuetyp = value
				Me.SendPropertyChanged("SettingValuetyp")
				Me.OnSettingValuetypChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

Partial Public Class AjKrypinGetUserKrypinResult
	
	Private _UserId As Integer
	
	Private _Presentation As String
	
	Private _BBUserMess As String
	
	Private _Avatar As String
	
	Private _ValdUserCss As System.Nullable(Of Integer)
	
	Private _KrypinBehorighet As Integer
	
	Private _LaserJustnu As System.Nullable(Of Integer)
	
	Private _DisplayName As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserId", DbType:="Int NOT NULL")>  _
	Public Property UserId() As Integer
		Get
			Return Me._UserId
		End Get
		Set
			If ((Me._UserId = value)  _
						= false) Then
				Me._UserId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Presentation", DbType:="NVarChar(500)")>  _
	Public Property Presentation() As String
		Get
			Return Me._Presentation
		End Get
		Set
			If (String.Equals(Me._Presentation, value) = false) Then
				Me._Presentation = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BBUserMess", DbType:="NVarChar(255)")>  _
	Public Property BBUserMess() As String
		Get
			Return Me._BBUserMess
		End Get
		Set
			If (String.Equals(Me._BBUserMess, value) = false) Then
				Me._BBUserMess = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Avatar", DbType:="NVarChar(255)")>  _
	Public Property Avatar() As String
		Get
			Return Me._Avatar
		End Get
		Set
			If (String.Equals(Me._Avatar, value) = false) Then
				Me._Avatar = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValdUserCss", DbType:="Int")>  _
	Public Property ValdUserCss() As System.Nullable(Of Integer)
		Get
			Return Me._ValdUserCss
		End Get
		Set
			If (Me._ValdUserCss.Equals(value) = false) Then
				Me._ValdUserCss = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KrypinBehorighet", DbType:="Int NOT NULL")>  _
	Public Property KrypinBehorighet() As Integer
		Get
			Return Me._KrypinBehorighet
		End Get
		Set
			If ((Me._KrypinBehorighet = value)  _
						= false) Then
				Me._KrypinBehorighet = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LaserJustnu", DbType:="Int")>  _
	Public Property LaserJustnu() As System.Nullable(Of Integer)
		Get
			Return Me._LaserJustnu
		End Get
		Set
			If (Me._LaserJustnu.Equals(value) = false) Then
				Me._LaserJustnu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DisplayName", DbType:="NVarChar(128) NOT NULL", CanBeNull:=false)>  _
	Public Property DisplayName() As String
		Get
			Return Me._DisplayName
		End Get
		Set
			If (String.Equals(Me._DisplayName, value) = false) Then
				Me._DisplayName = value
			End If
		End Set
	End Property
End Class

Partial Public Class AJKrypin_updateAvatarSettingResult
	
	Private _UserId As Integer
	
	Private _Avatar As String
	
	Private _Avatarid As Integer
	
	Private _Avatarnamn As String
	
	Private _Avatarsrc As String
	
	Private _LaserJustnu As System.Nullable(Of Integer)
	
	Private _ValdUserCss As System.Nullable(Of Integer)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserId", DbType:="Int NOT NULL")>  _
	Public Property UserId() As Integer
		Get
			Return Me._UserId
		End Get
		Set
			If ((Me._UserId = value)  _
						= false) Then
				Me._UserId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Avatar", DbType:="NVarChar(255)")>  _
	Public Property Avatar() As String
		Get
			Return Me._Avatar
		End Get
		Set
			If (String.Equals(Me._Avatar, value) = false) Then
				Me._Avatar = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Avatarid", DbType:="Int NOT NULL")>  _
	Public Property Avatarid() As Integer
		Get
			Return Me._Avatarid
		End Get
		Set
			If ((Me._Avatarid = value)  _
						= false) Then
				Me._Avatarid = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Avatarnamn", DbType:="NVarChar(50)")>  _
	Public Property Avatarnamn() As String
		Get
			Return Me._Avatarnamn
		End Get
		Set
			If (String.Equals(Me._Avatarnamn, value) = false) Then
				Me._Avatarnamn = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Avatarsrc", DbType:="NVarChar(250)")>  _
	Public Property Avatarsrc() As String
		Get
			Return Me._Avatarsrc
		End Get
		Set
			If (String.Equals(Me._Avatarsrc, value) = false) Then
				Me._Avatarsrc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LaserJustnu", DbType:="Int")>  _
	Public Property LaserJustnu() As System.Nullable(Of Integer)
		Get
			Return Me._LaserJustnu
		End Get
		Set
			If (Me._LaserJustnu.Equals(value) = false) Then
				Me._LaserJustnu = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValdUserCss", DbType:="Int")>  _
	Public Property ValdUserCss() As System.Nullable(Of Integer)
		Get
			Return Me._ValdUserCss
		End Get
		Set
			If (Me._ValdUserCss.Equals(value) = false) Then
				Me._ValdUserCss = value
			End If
		End Set
	End Property
End Class
