<?xml version="1.0" encoding="utf-8"?><Database Name="AJDNNDatabase_v5" Class="KrypinSettingsLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=AJDNNDatabase_v5;User ID=forfAdmin2" SettingsObjectName="KrypinSettings.My.MySettings" SettingsPropertyName="AJDNNDatabase_v5ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAJKrypinUserData" Member="tblAJKrypinUserDatas">
    <Type Name="tblAJKrypinUserData">
      <Column Name="KrypID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Presentation" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BBUserMess" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ValdUserCss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KrypinBehorighet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LaserJustnu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Visits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MeVisits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowMess" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAjKrypinAvatars" Member="tblAjKrypinAvatars">
    <Type Name="tblAjKrypinAvatar">
      <Column Name="Avatarid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Avatarnamn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Avatarsrc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Beskrivning" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAJKrypinSkin" Member="tblAJKrypinSkins">
    <Type Name="tblAJKrypinSkin">
      <Column Name="skinID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Skinnamn" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Skinsrc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Skinclass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAjKrypinUserSettings" Member="tblAjKrypinUserSettings">
    <Type Name="tblAjKrypinUserSetting">
      <Column Name="settingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="settingTypID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="settingValue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAjKrypinUserSettingsTyper" Member="tblAjKrypinUserSettingsTypers">
    <Type Name="tblAjKrypinUserSettingsTyper">
      <Column Name="SetId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Settingtyp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SettingValuetyp" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.AjKrypinGetUserKrypin" Method="AjKrypinGetUserKrypin">
    <Parameter Name="userid" Type="System.Int32" DbType="Int" />
    <ElementType Name="AjKrypinGetUserKrypinResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Presentation" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BBUserMess" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ValdUserCss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KrypinBehorighet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LaserJustnu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AJKrypin_updateAvatarSetting" Method="AJKrypin_updateAvatarSetting">
    <ElementType Name="AJKrypin_updateAvatarSettingResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Avatarid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Avatarnamn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Avatarsrc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LaserJustnu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValdUserCss" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>